// JavaScript Document
//Card
SPADE_SUIT = 0;
CLUB_SUIT = 1;
HEART_SUIT = 2;
DIAMOND_SUIT = 3;
SPECIAL_SUIT = 4;
CLOWN_RANK = 0;
THIEF_RANK = 1;
TORCH_RANK = 2;

//Hands
ROYAL_FLUSH = 6;
STRAIGHT_FLUSH = 5;
FLUSH = 4;
STRAIGHT = 3;
THREE_OF_A_KIND = 2;
PAIR = 1;